"""
AI Prompts for LittleStar
"""

from .daily_report import DAILY_REPORT_SYSTEM_PROMPT, DAILY_REPORT_USER_TEMPLATE
from .parenting_qa import PARENTING_QA_SYSTEM_PROMPT, PARENTING_QA_USER_TEMPLATE
from .weekly_report import WEEKLY_REPORT_SYSTEM_PROMPT, WEEKLY_REPORT_USER_TEMPLATE

__all__ = [
    "DAILY_REPORT_SYSTEM_PROMPT",
    "DAILY_REPORT_USER_TEMPLATE",
    "PARENTING_QA_SYSTEM_PROMPT",
    "PARENTING_QA_USER_TEMPLATE",
    "WEEKLY_REPORT_SYSTEM_PROMPT",
    "WEEKLY_REPORT_USER_TEMPLATE",
]
